# Site settings
title: "Lan"
description: "So I was feeling nostalgic~"
baseurl: ""
url: "http://lanxingjian.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "abt"
    url: /about
  - title: "git"
    url: http://github.com/lanxingjian
  - title: "rss"
    url: /feed.xml
